name: Copy desktop & mimetype

on:
  workflow_dispatch:
      # ...
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup
      run: make setup
    - name: Update the MIME database
      run: make update_database
    - name: Associate program with the following file type
      run: make associate
