name: Copy desktop & mimetype

on:
  workflow_run:
      workflows: [Copy desktop & mimetype]
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup
      run: make setup
